// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBiqngW4oxuxqK6JyqDOSH9CemUTm7AcA',
    appId: '1:376841969111:web:c40203cf0987a20739bf92',
    messagingSenderId: '376841969111',
    projectId: 'pickaservice-93d67',
    authDomain: 'pickaservice-93d67.firebaseapp.com',
    storageBucket: 'pickaservice-93d67.appspot.com',
    measurementId: 'G-RM99LLELZD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvXPIAkfGe-jt0svWRGdC9wMU1L_eceIo',
    appId: '1:376841969111:android:36101602301cf25139bf92',
    messagingSenderId: '376841969111',
    projectId: 'pickaservice-93d67',
    storageBucket: 'pickaservice-93d67.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5-Qt4Xn9gJdyOyhdAV71aSAxj0j8aWws',
    appId: '1:376841969111:ios:f8e76d6732ede0eb39bf92',
    messagingSenderId: '376841969111',
    projectId: 'pickaservice-93d67',
    storageBucket: 'pickaservice-93d67.appspot.com',
    iosBundleId: 'com.abhion.pickaservice.pickAService',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5-Qt4Xn9gJdyOyhdAV71aSAxj0j8aWws',
    appId: '1:376841969111:ios:d105afdea238c5a339bf92',
    messagingSenderId: '376841969111',
    projectId: 'pickaservice-93d67',
    storageBucket: 'pickaservice-93d67.appspot.com',
    iosBundleId: 'com.abhion.pickaservice.pickAService.RunnerTests',
  );
}
